import pandas as pd
df = pd.read_csv("cleaned_ecommerce_data.csv")
print("\nFIRST 5 ROWS:")
print(df.head())
print(f"\nDataset Shape: {df.shape}")
print("\nColumns:")
print(df.columns)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDataset Info:")
print(df.info())
print("\nBasic Statistics:")
print(df.describe(include='all'))
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_').str.replace(r'[^\w\s]', '', regex=True)
print("\nNull values after cleaning column names:")
print(df.isnull().sum())
df = df.dropna() 
df = df.drop_duplicates()
print(f"\nCleaned Data Shape: {df.shape}")
df.to_csv("cleaned_ecommerce_data.csv", index=False)
print("\nCleaned data saved to cleaned_ecommerce_data.csv")
if 'return_flag' in df.columns:
    print("\nReturn Flag Distribution:")
    print(df['return_flag'].value_counts())
df.to_csv("cleaned_ecommerce_data.csv", index=False)