import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
data = pd.read_csv("cleaned_ecommerce_data.csv")
plt.figure(figsize=(8,5))
sns.countplot(data=data, x='product_category', hue='return_status', palette='Set2')
plt.title('Return Rate by Product Category')
plt.xlabel('Product Category')
plt.ylabel('Count')
plt.xticks(rotation=30)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8,5))
sns.countplot(data=data, x='payment_method', hue='return_status', palette='pastel')
plt.title('Return Rate by Payment Method')
plt.xlabel('Payment Method')
plt.ylabel('Count')
plt.tight_layout()
plt.show()
plt.figure(figsize=(8,5))
sns.countplot(data=data, x='shipping_method', hue='return_status', palette='coolwarm')
plt.title('Return Rate by Shipping Method')
plt.xlabel('Shipping Method')
plt.ylabel('Count')
plt.tight_layout()
plt.show()
plt.figure(figsize=(6,5))
sns.countplot(data=data, x='user_gender', hue='return_status', palette='muted')
plt.title('Return Rate by Gender')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.tight_layout()                                  
plt.show()
bins = [18, 25, 35, 45, 55, 65]
labels = ['18-24', '25-34', '35-44', '45-54', '55-64']
data['age_group'] = pd.cut(data['user_age'], bins=bins, labels=labels)
plt.figure(figsize=(8,5))
sns.countplot(data=data, x='age_group', hue='return_status', palette='Set2')
plt.title('Return Rate by Age Group')
plt.xlabel('Age Group')
plt.ylabel('Count')
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,6))
top_locations = data['user_location'].value_counts().nlargest(10).index
filtered_data = data[data['user_location'].isin(top_locations)]
sns.countplot(data=filtered_data, x='user_location', hue='return_status', palette='flare')
plt.title('Return Rate by Top Locations')
plt.xlabel('User Location') 
plt.ylabel('Count') 
plt.xticks(rotation=45) 
plt.tight_layout()           
plt.show()
plt.figure(figsize=(8,5))
sns.histplot(data=data[data['return_status'] == 'Returned'], x='days_to_return', bins=30, kde=True, color='skyblue')
plt.title('Distribution of Days Taken to Return Products')
plt.xlabel('Days to Return')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()
